### PR TITLE
Lyn fixes

### PR DESCRIPTION
**Pull request by TheSmashBoy**
Info at the README.

### CODE REVIEW

**Comment by bb010g** [comment]
Could those be put into `CHANGELOG.md` instead of the README? Otherwise LGTM.

**Comment by TheSmashBoy** [comment]
@bb010g I don't know how to make a .md file. :/

 I figured a text document is enough.

**Comment by bb010g** [comment]
If someone could test this and confirm that it works, that would be great. I can't really test right now.

**Comment by TheSmashBoy** [comment]
@bb010g Purpa and I had tested these simultaneously. So it's good to go. Plus he showed me pictures of how her eye glitch was fixed as well as the Cosmetic problem being completely gone thanks to his proposed changes. Yeah. It's good to go.

**Pull request merged**
